name: TutorialLogin
description: Sistema de Login funcional
main: net.eduard.login.LoginPlugin
version: 1.0
authors: [Eduard]
author: Eduard
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  login:
    description: Entrar no servidor
    permission: comando.login
    usage: /<command> <password>
    alias: [logar,entrar]
  register:
    usage: /<command> <password> <confirm_passord>
    alias: [registrar]
    permission: comando.register
    description: Registrar no servidor